# Generated by Django 5.2.1 on 2025-05-26 10:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0003_alter_nodes_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nodes',
            unique_together={('name', 'creator')},
        ),
    ]
