# Generated by Django 5.2.1 on 2025-05-26 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0004_alter_nodes_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='NodesPch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes_pch_child', to='node_manager.nodes')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes_pch_parent', to='node_manager.nodes')),
            ],
        ),
    ]
