# Generated by Django 5.2.1 on 2025-05-27 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0005_nodes_level_nodespch'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='root_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root', to='node_manager.nodes'),
        ),
    ]
