# Generated by Django 5.2.1 on 2025-06-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0007_nodepiece_delete_nodepieces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodespch',
            name='child',
        ),
        migrations.RemoveField(
            model_name='nodespch',
            name='parent',
        ),
        migrations.DeleteModel(
            name='NodesAllowedUsers',
        ),
        migrations.DeleteModel(
            name='NodesPch',
        ),
    ]
